#!/usr/bin/env bash
#
# Generate real Terraform plan JSON for the demo change, entirely offline.
#
# What this does NOT do:
#   - contact AWS (the provider is configured with skip_* flags and mock credentials)
#   - read or refresh remote state (-refresh=false)
#   - create, modify or destroy any resource (plan only, never apply)
#   - require AWS credentials, a profile, or a region with an account behind it
#
# What it DOES need: the Terraform CLI, and network access to the public Terraform
# Registry on first run so `terraform init` can download the AWS provider. That
# download is free and involves no AWS account.
#
# The state file it plans against is a TEST FIXTURE representing a hypothetical
# already-deployed stack at reserved_concurrency = 10. It is not, and never was,
# real account state. See terraform/fixtures/README.md.

set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
tf_dir="${repo_root}/terraform"
fixture_state="${tf_dir}/fixtures/deployed-at-10.tfstate"
work_dir="${tf_dir}/.offline-plan"
output="${repo_root}/backend/lambda/changeproof/fixtures/terraform_plan.json"

if ! command -v terraform >/dev/null 2>&1; then
  echo "error: terraform CLI not found on PATH." >&2
  echo "Install it from https://developer.hashicorp.com/terraform/install - it is a" >&2
  echo "single free binary and needs no AWS account." >&2
  exit 1
fi

if [ ! -f "${fixture_state}" ]; then
  echo "error: fixture state not found at ${fixture_state}" >&2
  exit 1
fi

# Work on a copy so the committed fixture is never mutated by terraform.
rm -rf "${work_dir}"
mkdir -p "${work_dir}"
cp "${fixture_state}" "${work_dir}/terraform.tfstate"

echo "==> terraform init (downloads the AWS provider from the public registry)"
terraform -chdir="${tf_dir}" init -input=false -upgrade=false

echo "==> terraform plan (offline: -refresh=false, no AWS API calls)"
terraform -chdir="${tf_dir}" plan \
  -input=false \
  -refresh=false \
  -lock=false \
  -state="${work_dir}/terraform.tfstate" \
  -var "reserved_concurrency=100" \
  -out="${work_dir}/offline.tfplan"

echo "==> terraform show -json"
terraform -chdir="${tf_dir}" show -json "${work_dir}/offline.tfplan" > "${work_dir}/plan.json"

python - "$@" <<'PY' "${work_dir}/plan.json" "${output}"
import json
import sys

source, destination = sys.argv[-2], sys.argv[-1]
with open(source, encoding="utf-8") as handle:
    plan = json.load(handle)

plan = {
    "$fixture": (
        "Generated by scripts/generate_plan.sh from a TEST FIXTURE state file. "
        "Produced offline with -refresh=false and mock provider credentials. "
        "No AWS account was contacted and no resource exists."
    ),
    **plan,
}

with open(destination, "w", encoding="utf-8") as handle:
    json.dump(plan, handle, indent=2)
    handle.write("\n")

changes = [
    c for c in plan.get("resource_changes", [])
    if c.get("change", {}).get("actions") != ["no-op"]
]
print(f"wrote {destination}")
print(f"effective resource changes: {len(changes)}")
for change in changes:
    print(f"  {change['address']}: {'/'.join(change['change']['actions'])}")
PY

# The working directory holds a copy of the fixture state and an intermediate
# plan.json. Neither is an output worth keeping, and plan.json is not covered by
# .gitignore, so it is removed rather than left untracked.
rm -rf "${work_dir}"

echo "==> done. No AWS API call was made."
